Project/main/routes.py
from flask import render_template,request,Blueprint
from Project.main.forms import search_projects
from Project.models import User,Project


main=Blueprint("main",__name__)


@main.route("/")
@main.route("/home",methods=['GET','POST'])
def home():
    page=request.args.get('page',1,type=int)
    form=search_projects()
    if form.validate_on_submit():
        if form.category.data[0]=='teacher_name':
            projects=Project.query.filter(Project.user.has(User.username==form.search.data)).order_by(Project.created_at.desc()).all()
            return render_template("home.html",projects=projects,form=form)
        elif form.category.data[0]=='project_name':
            projects=Project.query.filter_by(title=form.search.data).all()
            return render_template("home.html",projects=projects,form=form)
        elif form.category.data[0]=='skill':
            skill=form.search.data
            list=Project.query.order_by(Project.created_at.desc()).all()
            projects=[]
            for i in list:
                if skill in i.skills:
                    projects.append(i)
            return render_template("home.html",projects=projects,form=form)
    projects=Project.query.order_by(Project.created_at.desc()).paginate(page=page,max_per_page=6)
    return render_template("home.html",projects=projects,page=page,form=form)

Project/projects/routes.py
import os
from Project import db
from flask import render_template,flash,redirect,request,url_for,abort,Blueprint,current_app
from Project.projects.forms import project_form,submit_project,evaluate_project
from Project.models import Project,Project_Taken,Submission,Evaluation
from flask_login import current_user,login_required
from Project.projects.utils import save_file


projects=Blueprint("projects",__name__)


@projects.route("/project/add",methods=['GET','POST'])
@login_required
def add_project():
    if current_user.role=='student':
        abort(403)
    form=project_form()
    if form.validate_on_submit():
        filename=""
        if form.file_pdf.data:
            filename=save_file(form.file_pdf.data)
        else:
            filename="No pdf"
        post=Project(title=form.title.data,
                     description=form.description.data,
                     skills=form.skills.data,
                     user=current_user,
                     descriptive_pdf=filename)
        current_user.total_projects+=1
        db.session.add(post)
        db.session.commit()
        flash("A new project has been added","success")
        return redirect(url_for("users.profile"))
    elif form.errors:
        flash("Could not add the project","danger")
    return render_template("project_edit.html",form=form,legend="Add New Project")


@projects.route("/project/update/<int:project_id>",methods=['GET','POST'])
@login_required
def update_project(project_id):
    if current_user.role=='student':
        abort(403)
    form=project_form()
    project=Project.query.get(project_id)
    project_name=project.title.strip()
    src=request.args.get("act")
    if form.validate_on_submit():
        if form.file_pdf.data:
            file_name=save_file(form.file_pdf.data)
            if project.descriptive_pdf!="No pdf":
                path=os.path.join(current_app.root_path,'static/project_details',project.descriptive_pdf)
                if os.path.exists(path):
                    os.remove(path)
            project.descriptive_pdf=file_name
            db.session.commit()
        if form.title.data!=project.title or form.description.data!=project.description or form.skills.data!=project.skills:
            project.title=form.title.data
            project.description=form.description.data
            project.skills=form.skills.data
            db.session.commit()
        flash(f"\"{project_name}\" has been updated successfully","success")
        if src:
            return redirect(url_for("projects.more_info"))
        else:
            return redirect(url_for("users.profile"))   
    elif request.method=='GET':
        form.title.data=project.title
        form.description.data=project.description
        form.skills.data=project.skills
    elif form.errors:
        flash(f"\"{project_name}\" could not be updated","danger")
    return render_template("project_edit.html",form=form,legend="Update Project",id="update")


@projects.route("/project/delete/<int:project_id>",methods=['GET','POST'])
@login_required
def delete_project(project_id):
    if current_user.role=='student':
        abort(403)
    project=Project.query.get(project_id)
    project.user.total_projects-=1
    if project.evaluation:
        project.user.total_projects_evaluated-=len(project.evaluation)
        for i in project.evaluation:
            i.submission.user.total_projects_evaluated-=1
    if project.submission:
        project.user.total_projects_submitted-=len(project.submission)
        for i in project.submission:
            i.user.total_projects_submitted-=1
    if project.project_taken_by:
        for i in project.project_taken_by:
            i.user.total_projects_taken-=1
    project_name=project.title.strip()
    db.session.delete(project)
    db.session.commit()
    src=request.args.get("act")
    flash(f"\"{project_name}\" has been deleted successfully","success")
    if src:
        return redirect(url_for("projects.more_info"))
    else:
        return redirect(url_for("users.profile"))
    

@projects.route("/project/take/<int:project_id>")
@login_required
def take_proj(project_id):
    if current_user.role=='teacher':
        abort(403)
    project=Project.query.get(project_id)
    if Project_Taken.query.filter_by(project=project,user=current_user).first():
        flash("Project already taken","danger")
        page=request.args.get("page",1,type=int)
        return redirect(url_for("main.home",page=page))
    if Submission.query.filter_by(project=project,user=current_user).first():
        submission=Submission.query.filter_by(project=project,user=current_user).first()
        if not Evaluation.query.filter_by(project=project,submission=submission).first():
            flash("Project has already been submitted once. You can retake the project after it has been evaluated.","danger")
            page=request.args.get("page",1,type=int)
            return redirect(url_for("main.home",page=page))
    project_taken=Project_Taken(project=project,user=current_user)
    current_user.total_projects_taken+=1
    project.user_count+=1
    db.session.add(project_taken)
    db.session.commit()
    flash("The Project was taken","success")
    page=request.args.get("page",1,type=int)
    return redirect(url_for("main.home",page=page))


@projects.route("/project/student/remove/<int:project_taken_id>",methods=['GET','POST'])
@login_required
def remove_proj_taken(project_taken_id):
    if current_user.role=='teacher':
        abort(403)
    project_taken=Project_Taken.query.get(project_taken_id)
    project_taken.project.user_count-=1
    project_taken.user.total_projects_taken-=1
    project_name=project_taken.project.title.strip()
    db.session.delete(project_taken)
    db.session.commit()
    flash(f"\"{project_name}\" has been removed","success")
    src=request.args.get('act')
    if src:
        return redirect(url_for("projects.more_info_taken"))
    else:
        return redirect(url_for("users.profile"))


@projects.route("/project/student/submit/<int:project_taken_id>",methods=['GET','POST'])
@login_required
def submit_proj_taken(project_taken_id):
    if current_user.role=='teacher':
        abort(403)
    project_taken=Project_Taken.query.get(project_taken_id)
    form=submit_project()
    src=request.args.get("act")
    if form.validate_on_submit():
        submit=Submission(info=form.info.data,
                          submission_link=form.project_link.data,
                          user=current_user,
                          project=project_taken.project
                          )
        teacher_name=project_taken.project.user.username.strip()
        project_taken.user.total_projects_taken-=1
        project_taken.user.total_projects_submitted+=1
        project_taken.project.user.total_projects_submitted+=1
        project_taken.project.user_count-=1
        db.session.delete(project_taken)
        db.session.add(submit)
        db.session.commit()
        flash(f"The project has been submitted successfully to \"{teacher_name}\"","success")
        if src:
            return redirect(url_for("projects.more_info_taken"))
        else:
            return redirect(url_for("users.profile"))
    elif form.errors:
        flash("Project could not be submitted","danger")
        print(form.errors)
    return render_template("project_submit.html",form=form,legend="Submit Project")


@projects.route("/project/details/<int:project_id>",methods=['GET','POST'])
def project_details(project_id):
    project=Project.query.get(project_id)
    img_src=url_for("static",filename="/profile_pics/"+project.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+project.descriptive_pdf)
    return render_template("project_details.html",user=project.user,img_src=img_src,project=project,pdf=pdf)


@projects.route("/project/evaluate/<int:id>")
@login_required
def evaluate(id):
    submission=Submission.query.get(id)
    img_src=url_for("static",filename="/profile_pics/"+submission.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+submission.project.descriptive_pdf)
    return render_template("evaluate.html",submission=submission,pdf=pdf,img_src=img_src)


@projects.route("/project/evaluate/form/<int:id>",methods=["GET","POST"])
@login_required
def evaluate_form(id):
    form=evaluate_project()
    submission=Submission.query.get(id)
    src=request.args.get("act")
    if form.validate_on_submit():
        evaluation=Evaluation(score=form.score.data/10,
                              feedback=form.feedback.data,
                              submission=submission,
                              user=current_user,
                              project=submission.project
                              )
        current_user.total_projects_evaluated+=1
        submission.user.total_projects_evaluated+=1
        db.session.add(evaluation)
        db.session.commit()
        flash("You reviews have been submitted","success")
        if src:
            return redirect(url_for("projects.more_info_submission"))
        else:
            return redirect(url_for("users.profile"))
    return render_template("evaluate_form.html",legend="Reviews",form=form)


@projects.route("/project/reviews/<int:id>")
@login_required
def reviews(id):
    evaluation=Evaluation.query.get(id)
    submission=evaluation.submission
    img_src=url_for("static",filename="/profile_pics/"+evaluation.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+submission.project.descriptive_pdf)
    return render_template("reviews.html",evaluation=evaluation,submission=submission,img_src=img_src,pdf=pdf)


@projects.route("/profile/moreinfo/projects")
@login_required
def more_info():
    projects=current_user.project
    projects.reverse()
    return render_template("more-info/more_projects.html",projects=projects,title="Projects")


@projects.route("/profile/moreinfo/submission")
@login_required

Project/users/routes.py
import os
from Project import db,bcrypt
from flask import render_template,flash,redirect,request,url_for,Blueprint
from Project.users.forms import registeration_form,login_form,update_profile_form,reset_password_email_form,reset_password_form
from Project.models import User,Submission
from flask_login import login_user,current_user,login_required,logout_user
from Project.users.utils import save_pic,send_mail

users=Blueprint("users",__name__)

@users.route("/register",methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form=registeration_form()
    if form.validate_on_submit():
        password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,
                  email=form.email.data,
                  password=password,
                  role=form.category.data[0])
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created successfully","success")
        return redirect(url_for('users.login'))
    return render_template("register.html",form=form)


@users.route("/login",methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form=login_form()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password,form.password.data) and user.role==form.category.data[0]:
                login_user(user,remember=False)
                flash("You have been logged in successfully","success")
                return redirect(url_for("main.home"))
            else:
                flash("Login unsuccessful check your details","danger")
        else:
                flash("User doesn't exists","danger")
                return redirect(url_for("users.register"))
    return render_template("login.html",form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/profile")
@login_required
def profile():
    img_src=url_for("static",filename="/profile_pics/"+current_user.profile_picture)
    if current_user.role=='teacher':
        project_loadmore=False
        submission_loadmore=False
        evaluation_loadmore=False
        projects=current_user.project
        if len(projects)>5:
            project_loadmore=True
        submissions=[]
        for i in projects:
            submission=Submission.query.filter_by(project=i).all()
            submissions.extend(submission)
        projects.reverse()
        submissions.reverse()
        if len(submissions)>5:
            submission_loadmore=True
        evaluation=current_user.evaluation
        evaluation.reverse()
        if len(evaluation)>5:
            evaluation_loadmore=True
        return render_template("profile_teacher.html",img_src=img_src,projects=projects[:5],submissions=submissions[:5],
                               evaluation=evaluation[:5],plm=project_loadmore,slm=submission_loadmore,elm=evaluation_loadmore)
    elif current_user.role=='student':
        project_loadmore=False
        submission_loadmore=False
        projects=current_user.project_taken
        projects.reverse()
        if len(projects)>5:
            project_loadmore=True
        submissions=current_user.submission
        submissions.reverse()
        if len(submissions)>5:
            submission_loadmore=True
        return render_template("profile_student.html",img_src=img_src,projects=projects[:5],submissions=submissions[:5],plm=project_loadmore,slm=submission_loadmore)


@users.route("/profile/update",methods=["GET","POST"])
@login_required
def update_profile():
    form=update_profile_form()
    if form.validate_on_submit():
        if form.image.data:
            file_name=save_pic(form.image.data)
            if current_user.profile_picture!="default.png":
                path=os.path.join(users.root_path,'static/profile_pics',current_user.profile_picture)
                if os.path.exists(path):
                    os.remove(path)
            current_user.profile_picture=file_name
            db.session.commit()
        if current_user.username!=form.username.data or current_user.email!=form.email.data:
            current_user.username=form.username.data
            current_user.email=form.email.data
            db.session.commit()
        flash("Changes made","success")
        return redirect(url_for("users.profile"))
    elif request.method=="GET":
        form.username.data=current_user.username
        form.email.data=current_user.email
    return render_template("update_profile.html",form=form)


@users.route("/reset_password_email",methods=['GET','POST'])
def reset_password_email():
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    form=reset_password_email_form()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user:
            send_mail(user)
        flash('You will recieve an email with the reset password link if the email is registered','info')
        return redirect(url_for("users.login"))
    return render_template("reset_password/reset_password_email.html",form=form)


@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("home"))
    
    user_id=User.verify_token(token)
    if user_id is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for("users.reset_password_email"))
    form=reset_password_form()
    if form.validate_on_submit():
        user=User.query.get(user_id['user_id'])
        user.password=bcrypt.generate_password_hash(form.password.data)
        db.session.commit()
        flash("The password has been changed successfully","success")
        return redirect(url_for("users.login"))
    return render_template("reset_password/reset_password.html",form=form)

Project/templates/evaluate.html
{% extends "layout.html" %}
{% block content %}
    <main class="container dashboard">
        <div class="details-head">
            <i class="fa-solid fa-user fa-2x"></i>
            <h1>Submitted By</h1>
        </div>
        <div class="details-header">
            <div class="profile-header-details">
                <img class="rounded-circle account-img img-profile" src="{{img_src}}">
                <div class="details">
                    <h2>Submitted by : {{submission.user.username}}</h2>
                    <p>His/Her email : {{submission.user.email}}</p>
                    <p>Submitted on : {{submission.submitted_at.strftime("%Y-%m-%d")}}</p>
                    {% if request.args.get("act") %}
                        <a class="btn btn-success" style="color:white;font-weight: 1000;" href="{{url_for('projects.evaluate_form',id=submission.id,act=request.args.get('act'))}}">Evaluate</a>
                    {% else %}
                        <a class="btn btn-success" style="color:white;font-weight: 1000;" href="{{url_for('projects.evaluate_form',id=submission.id)}}">Evaluate</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="details-head">
            <i class="fa-solid fa-circle-info fa-2x"></i>
            <h1>Submission Details</h1>
        </div>
        <div class="info-header">
            <div class="info-section">
                <h3>Description</h3>
                <div>{{submission.info}}</div>
            </div>
            <div class="info-section">
            <a class="btn btn-info info-btn" href="{{submission.submission_link}}">Repository Link</a>
            </div>
        </div>
        <div class="details-head">
            <i class="fa-solid fa-bookmark fa-lg"></i>
            <h1>Project's Details</h1>
        </div>
        <div class="info-header">
            <div class="info-section">
                <h3>Title</h3>
                <h5>{{submission.project.title}}</h5>
            </div>
            <div class="info-section">
                <h3>Description</h3>
                <div>{{submission.project.description}}</div>
            </div>
            <div class="info-section skills">
                <h3>Skills Required : </h3>
                <ul>
                    {% for i in submission.project.skills.split(',') %}
                    <li>{{i.strip()}}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="info-section">
                {% if submission.project.descriptive_pdf == "No pdf" %}
                    <a class="btn btn-dark info-btn" href="{{url_for('projects.project_details',project_id=submission.project.id)}}" target="_blank">No pdf uploaded by the teacher</a>
                {% else %}
                    <a class="button button-diff info-btn" href="{{pdf}}" target="_blank">Open pdf with details</a>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock content %}

Project/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <main class="container">
    <section class="top-section">
      <h1>Discover Great Academic Opportunities</h1>
      <p>Connect with professors and find research projects that suits your skills</p>
    </section>

    <section class="search">
      <div class="search-container">
        <form action="" method="POST">
          {{form.hidden_tag()}}
          <div class="search-here">
            <div class="search-category">
                {% for i in form.category %}
                  <span>{{i()}}</span>
                {% endfor %}
            </div>
            <div class="search-box">
              {{form.search(placeholder=form.search.label.text,class="search-input")}}
            </div>
            <div>
              {{form.submit(class="search-btn button button-diff")}}
            </div>
          </div>
        </form>
      </div>
    </section>

    <section>
      <div class="projects-grid">
        {% for project in projects %}
        <article class="project-card">
          <div class="project-content">
            <div class="project-user-profile">
              <img class="rounded-circle account-img project-image" src="{{url_for('static',filename='/profile_pics/'+project.user.profile_picture)}}">
              <div class="project-profile">
                <span class="uploader">Uploaded by : {{project.user.username}}</span>
                <span class="upload-date">
                  <i class="fa-regular fa-calendar"></i>
                  Uploaded on : 
                  {{project.created_at.strftime("%Y-%m-%d")}}
                </span>
              </div>
            </div>
            <h3>{{project.title}}</h3>
            <p>{{project.description}}</p>
            <div class="skills">
              <h4>Skills Required : </h4>
              <ul>
                {% for i in project.skills.split(',') %}
                  <li>{{i.strip()}}</li>
                {% endfor %}
              </ul>
            </div>
              <div class="project-footer">
                <a class="button button-diff button-home" href="{{url_for('projects.project_details',project_id=project.id)}}">Details</a>
                {% if current_user.role=='student' %}
                <a class="button button-diff button-home" href="{{url_for('projects.take_proj',project_id=project.id,page=request.args.get('page'))}}">Apply Now</a>
                {% endif %}
              </div> 
          </div>
        </article>
        {% endfor %}
      </div>
    </section>
    <div class="paginate">
      {% if page %}
        {% for i in projects.iter_pages(left_edge=1, right_edge=1,left_current=1,right_current=1) %}
          {% if i %}
            {% if i==page %}
              <a class="btn btn-info" href="{{url_for('main.home',page=i)}}">{{i}}</a>
            {% else %}
              <a class="btn btn-outline-info" href="{{url_for('main.home',page=i)}}">{{i}}</a>
            {% endif %}
          {% else %}
            <p>...</p>
          {% endif %}
        {% endfor %}
      {% endif %}
    </div>
    <section class="benefits">
      <h2>Why Join Research Projects?</h2>
      <div class="benefits-grid">
        <div class="benefit-card">
          <div class="benefit-icon">
            <i class="fa-solid fa-book"></i>
          </div>
          <h3>Gain Experience</h3>
          <p>Work on real-world research projects and build your academic portfolio and skills</p>
        </div>
        <div class="benefit-card">
          <div class="benefit-icon">
            <i class="fa-solid fa-id-card-clip"></i>
          </div>
          <h3>Network with Professors</h3>
          <p>Build relationships with leading academics in your field</p>
        </div>
        <div class="benefit-card">
          <div class="benefit-icon">
            <i class="fa-solid fa-graduation-cap"></i>
          </div>
          <h3>Advance Your Career</h3>
          <p>Enhance your resume and open doors to future opportunities</p>
        </div>
      </div>
    </section>
  </main>
{% endblock content %}

Project/templates/profile_teacher.html
{% extends "layout.html" %}
{% block content %}
    <main class="container dashboard">
    <div class="profile-header">
      <img class="rounded-circle account-img img-profile" src="{{img_src}}">
      <div class="details">
        <h2>{{current_user.username}}</h2>
        <p>{{current_user.email}}</p>
        <p>{{current_user.role.capitalize()}}</p>
        <a class="button" href="{{url_for('users.update_profile')}}">Edit Profile</a>
      </div>
    </div>

    <div class="proj-grid">
      <div class="proj-card">
        <div class="proj-content">
          <h4>Active Projects</h4>
          <span class="proj-number">{{current_user.total_projects}}</span>
        </div>
        <p>Currently accepting applications</p>
      </div>
      
      <div class="proj-card">
        <div class="proj-content">
          <h4>Submissions</h4>
          <span class="proj-number">{{current_user.total_projects_submitted}}</span>
        </div>
        <p>Project Submissions</p>
      </div>
      
      <div class="proj-card">
        <div class="proj-content">
          <h4>Submissions Evaluated</h4>
          <span class="proj-number">{{current_user.total_projects_evaluated}}</span>
        </div>
        <p>Remarks Given</p>
      </div>
    </div>

    <div class="projects-table-outer">
    <div class="projects-table-container">
      <div class="table-header">
        <h2>Projects</h2>
        <a class="button button-diff" href="{{url_for('projects.add_project')}}">Add Project</a>
      </div>

      <div class="table-responsive">
        <table>
          <thead>
            <tr>
              <th>Project's Title</th>
              <th>Upload Date</th>
              <th>Active Workers</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
              {% for i in projects %}
              <tr>
                <td>{{i.title}}</td>
                <td>{{i.created_at.strftime("%Y-%m-%d")}}</td>
                <td>{{i.user_count}}</td>
                <td><a class="btn btn-info" href="{{url_for('projects.update_project',project_id=i.id)}}">Update</a></td>
                <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
                
                  <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                          <div class="modal-content">
                          <div class="modal-header">
                              <h5 class="modal-title" style="color:black;" id="deleteModalLabel">Delete Project Permanently</h5>
                              <button type="button" style="margin:0.01rem;" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                          </div>
                          <div class="modal-footer">
                              <form action="{{url_for('projects.delete_project',project_id=i.id)}}" method="POST">
                                  <input type="submit" class="btn btn-danger" value="Delete">
                              </form>
                          </div>
                          </div>
                      </div>
                    </div>
                
                </td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="outer-position-btn">
    {% if plm %}
      <a class="btn btn-outline-primary position-btn" href="{{url_for('projects.more_info')}}">Load More</a>
    {% endif %}
    </div>
    </div>
    
    <div class="projects-table-outer">
    <div class="projects-table-container">
      <div class="table-header">
        <h2>Submissions</h2>
      </div>
      <div class="table-responsive">
        <table>
          <thead>
            <tr>
              <th>Project's Title</th>
              <th>Upload Date</th>
              <th>Submitted by</th>
              <th>Submitted on</th>
              <th>Evaluate</th>
            </tr>
          </thead>
          <tbody>
              {% for i in submissions %}
              <tr>
                <td>{{i.project.title}}</td>
                <td>{{i.project.created_at.strftime("%Y-%m-%d")}}</td>
                <td>{{i.user.username}}</td>
                <td>{{i.submitted_at.strftime("%Y-%m-%d")}}</td>
                {% if i.evaluation %}
                  <td><a class="btn btn-dark" >Evaluated</a></td>
                {% else %}
                  <td><a class="btn btn-outline-success" href="{{url_for('projects.evaluate',id=i.id)}}">Evaluate</a></td>
                {% endif %}    
                </td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="outer-position-btn">
    {% if slm %}
      <a class="btn btn-outline-primary position-btn" href="{{url_for('projects.more_info_submission')}}">Load More</a>
    {% endif %}
    </div>
    </div>

    <div class="projects-table-outer">
    <div class="projects-table-container">
      <div class="table-header">
        <h2>Evaluated Projects</h2>
      </div>
      <div class="table-responsive">
        <table>
          <thead>
            <tr>
              <th>Project's Title</th>
              <th>Submitted on</th>
              <th>Submitted by</th>
              <th>Evaluated on</th>
              <th>Reviews given</th>
            </tr>
          </thead>
          <tbody>
            <tbody>
              {% for i in evaluation %}
              <tr>
                <td>{{i.project.title}}</td>
                <td>{{i.project.created_at.strftime("%Y-%m-%d")}}</td>
                <td>{{i.submission.user.username}}</td>
                <td>{{i.submission.submitted_at.strftime("%Y-%m-%d")}}</td>
                <td><a class="btn btn-outline-info" href="{{url_for('projects.reviews',id=i.id)}}">See Reviews given</a></td>
              </tr>
              {% endfor %}
          </tbody>
          </tbody>
        </table>
      </div>
    </div>
    <div class="outer-position-btn">
    {% if elm %}
      <a class="btn btn-outline-primary position-btn" href="{{url_for('projects.more_info_evaluation')}}">Load More</a>
    {% endif %}
    </div>
    </div>

  </main>
{% endblock content %}