Project/projects/routes.py
import os
from Project import db
from flask import render_template,flash,redirect,request,url_for,abort,Blueprint,current_app
from Project.projects.forms import project_form,submit_project,evaluate_project
from Project.models import Project,Project_Taken,Submission,Evaluation
from flask_login import current_user,login_required
from Project.projects.utils import save_file


projects=Blueprint("projects",__name__)


@projects.route("/project/add",methods=['GET','POST'])
@login_required
def add_project():
    if current_user.role=='student':
        abort(403)
    form=project_form()
    if form.validate_on_submit():
        filename=""
        if form.file_pdf.data:
            filename=save_file(form.file_pdf.data)
        else:
            filename="No pdf"
        post=Project(title=form.title.data,
                     description=form.description.data,
                     skills=form.skills.data,
                     user=current_user,
                     descriptive_pdf=filename)
        current_user.total_projects+=1
        db.session.add(post)
        db.session.commit()
        flash("A new project has been added","success")
        return redirect(url_for("users.profile"))
    elif form.errors:
        flash("Could not add the project","danger")
    return render_template("project_edit.html",form=form,legend="Add New Project")


@projects.route("/project/update/<int:project_id>",methods=['GET','POST'])
@login_required
def update_project(project_id):
    if current_user.role=='student':
        abort(403)
    form=project_form()
    project=Project.query.get(project_id)
    project_name=project.title.strip()
    src=request.args.get("act")
    if form.validate_on_submit():
        if form.file_pdf.data:
            file_name=save_file(form.file_pdf.data)
            if project.descriptive_pdf!="No pdf":
                path=os.path.join(current_app.root_path,'static/project_details',project.descriptive_pdf)
                if os.path.exists(path):
                    os.remove(path)
            project.descriptive_pdf=file_name
            db.session.commit()
        if form.title.data!=project.title or form.description.data!=project.description or form.skills.data!=project.skills:
            project.title=form.title.data
            project.description=form.description.data
            project.skills=form.skills.data
            db.session.commit()
        flash(f"\"{project_name}\" has been updated successfully","success")
        if src:
            return redirect(url_for("projects.more_info"))
        else:
            return redirect(url_for("users.profile"))   
    elif request.method=='GET':
        form.title.data=project.title
        form.description.data=project.description
        form.skills.data=project.skills
    elif form.errors:
        flash(f"\"{project_name}\" could not be updated","danger")
    return render_template("project_edit.html",form=form,legend="Update Project",id="update")


@projects.route("/project/delete/<int:project_id>",methods=['GET','POST'])
@login_required
def delete_project(project_id):
    if current_user.role=='student':
        abort(403)
    project=Project.query.get(project_id)
    project.user.total_projects-=1
    if project.evaluation:
        project.user.total_projects_evaluated-=len(project.evaluation)
        for i in project.evaluation:
            i.submission.user.total_projects_evaluated-=1
    if project.submission:
        project.user.total_projects_submitted-=len(project.submission)
        for i in project.submission:
            i.user.total_projects_submitted-=1
    if project.project_taken_by:
        for i in project.project_taken_by:
            i.user.total_projects_taken-=1
    project_name=project.title.strip()
    db.session.delete(project)
    db.session.commit()
    src=request.args.get("act")
    flash(f"\"{project_name}\" has been deleted successfully","success")
    if src:
        return redirect(url_for("projects.more_info"))
    else:
        return redirect(url_for("users.profile"))
    

@projects.route("/project/take/<int:project_id>")
@login_required
def take_proj(project_id):
    if current_user.role=='teacher':
        abort(403)
    project=Project.query.get(project_id)
    if Project_Taken.query.filter_by(project=project,user=current_user).first():
        flash("Project already taken","danger")
        page=request.args.get("page",1,type=int)
        return redirect(url_for("main.home",page=page))
    if Submission.query.filter_by(project=project,user=current_user).first():
        submission=Submission.query.filter_by(project=project,user=current_user).first()
        if not Evaluation.query.filter_by(project=project,submission=submission).first():
            flash("Project has already been submitted once. You can retake the project after it has been evaluated.","danger")
            page=request.args.get("page",1,type=int)
            return redirect(url_for("main.home",page=page))
    project_taken=Project_Taken(project=project,user=current_user)
    current_user.total_projects_taken+=1
    project.user_count+=1
    db.session.add(project_taken)
    db.session.commit()
    flash("The Project was taken","success")
    page=request.args.get("page",1,type=int)
    return redirect(url_for("main.home",page=page))


@projects.route("/project/student/remove/<int:project_taken_id>",methods=['GET','POST'])
@login_required
def remove_proj_taken(project_taken_id):
    if current_user.role=='teacher':
        abort(403)
    project_taken=Project_Taken.query.get(project_taken_id)
    project_taken.project.user_count-=1
    project_taken.user.total_projects_taken-=1
    project_name=project_taken.project.title.strip()
    db.session.delete(project_taken)
    db.session.commit()
    flash(f"\"{project_name}\" has been removed","success")
    src=request.args.get('act')
    if src:
        return redirect(url_for("projects.more_info_taken"))
    else:
        return redirect(url_for("users.profile"))


@projects.route("/project/student/submit/<int:project_taken_id>",methods=['GET','POST'])
@login_required
def submit_proj_taken(project_taken_id):
    if current_user.role=='teacher':
        abort(403)
    project_taken=Project_Taken.query.get(project_taken_id)
    form=submit_project()
    src=request.args.get("act")
    if form.validate_on_submit():
        submit=Submission(info=form.info.data,
                          submission_link=form.project_link.data,
                          user=current_user,
                          project=project_taken.project
                          )
        teacher_name=project_taken.project.user.username.strip()
        project_taken.user.total_projects_taken-=1
        project_taken.user.total_projects_submitted+=1
        project_taken.project.user.total_projects_submitted+=1
        project_taken.project.user_count-=1
        db.session.delete(project_taken)
        db.session.add(submit)
        db.session.commit()
        flash(f"The project has been submitted successfully to \"{teacher_name}\"","success")
        if src:
            return redirect(url_for("projects.more_info_taken"))
        else:
            return redirect(url_for("users.profile"))
    elif form.errors:
        flash("Project could not be submitted","danger")
        print(form.errors)
    return render_template("project_submit.html",form=form,legend="Submit Project")


@projects.route("/project/details/<int:project_id>",methods=['GET','POST'])
def project_details(project_id):
    project=Project.query.get(project_id)
    img_src=url_for("static",filename="/profile_pics/"+project.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+project.descriptive_pdf)
    return render_template("project_details.html",user=project.user,img_src=img_src,project=project,pdf=pdf)


@projects.route("/project/evaluate/<int:id>")
@login_required
def evaluate(id):
    submission=Submission.query.get(id)
    img_src=url_for("static",filename="/profile_pics/"+submission.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+submission.project.descriptive_pdf)
    return render_template("evaluate.html",submission=submission,pdf=pdf,img_src=img_src)


@projects.route("/project/evaluate/form/<int:id>",methods=["GET","POST"])
@login_required
def evaluate_form(id):
    form=evaluate_project()
    submission=Submission.query.get(id)
    src=request.args.get("act")
    if form.validate_on_submit():
        evaluation=Evaluation(score=form.score.data/10,
                              feedback=form.feedback.data,
                              submission=submission,
                              user=current_user,
                              project=submission.project
                              )
        current_user.total_projects_evaluated+=1
        submission.user.total_projects_evaluated+=1
        db.session.add(evaluation)
        db.session.commit()
        flash("You reviews have been submitted","success")
        if src:
            return redirect(url_for("projects.more_info_submission"))
        else:
            return redirect(url_for("users.profile"))
    return render_template("evaluate_form.html",legend="Reviews",form=form)


@projects.route("/project/reviews/<int:id>")
@login_required
def reviews(id):
    evaluation=Evaluation.query.get(id)
    submission=evaluation.submission
    img_src=url_for("static",filename="/profile_pics/"+evaluation.user.profile_picture)
    pdf=url_for("static",filename="/project_details/"+submission.project.descriptive_pdf)
    return render_template("reviews.html",evaluation=evaluation,submission=submission,img_src=img_src,pdf=pdf)


@projects.route("/profile/moreinfo/projects")
@login_required
def more_info():
    projects=current_user.project
    projects.reverse()
    return render_template("more-info/more_projects.html",projects=projects,title="Projects")


@projects.route("/profile/moreinfo/submission")
@login_required

Project/templates/more-info/more-evaluation.html
{% extends "more-info/more-info-layout.html" %}
{% block label %}Evaluated Projects{% endblock label %}
{% block headings %}
    <th>Project's Title</th>
    <th>Submitted on</th>
    <th>Submitted by</th>
    <th>Evaluated on</th>
    <th>Reviews given</th>
{% endblock headings %}
{% block data %}
    {% for i in evaluation %}
        <tr>
            <td>{{i.project.title}}</td>
            <td>{{i.project.created_at.strftime("%Y-%m-%d")}}</td>
            <td>{{i.submission.user.username}}</td>
            <td>{{i.submission.submitted_at.strftime("%Y-%m-%d")}}</td>
            <td><a class="btn btn-outline-info" href="{{url_for('projects.reviews',id=i.id)}}">See Reviews given</a></td>
        </tr>
    {% endfor %}
{% endblock data %}

Project/templates/more-info/more-info-layout.html
{% extends "layout.html" %}
{% block content %}
<div class="more-info-outer">
    <div class="projects-table-container">
      <div class="table-header">
        <h2>{% block label %}{% endblock label %}</h2>
        {% if title=='Projects' %}
          <a class="button button-diff" href="{{url_for('projects.add_project')}}">Add Project</a>
        {% endif %}
      </div>

      <div class="table-responsive">
        <table>
          <thead>
            <tr>
              {% block headings%}
              {% endblock headings%}
            </tr>
          </thead>
          <tbody>
              {% block data %}
              {% endblock data %}
          </tbody>
        </table>
      </div>
    </div>
</div>
{% endblock content %}

Project/templates/more-info/more-submission.html
{% extends "more-info/more-info-layout.html" %}
{% block label %}Submissions{% endblock label %}
{% block headings %}
    <th>Project's Title</th>
    <th>Upload Date</th>
    <th>Submitted by</th>
    <th>Submitted on</th>
    <th>Evaluate</th>
{% endblock headings %}
{% block data %}
    {% for i in submissions %}
        <tr>
            <td>{{i.project.title}}</td>
            <td>{{i.project.created_at.strftime("%Y-%m-%d")}}</td>
            <td>{{i.user.username}}</td>
            <td>{{i.submitted_at.strftime("%Y-%m-%d")}}</td>
            {% if i.evaluation %}
                <td><a class="btn btn-dark" >Evaluated</a></td>
            {% else %}
                <td><a class="btn btn-outline-success" href="{{url_for('projects.evaluate',id=i.id,act='submission')}}">Evaluate</a></td>
            {% endif %}    
            </td>
        </tr>
    {% endfor %}
{% endblock data %}

Project/templates/more-info/more-submitted.html
{% extends "more-info/more-info-layout.html" %}
{% block label %}Projects Submitted{% endblock label %}
{% block headings %}
    <th>Project's Title</th>
    <th>Upload Date</th>
    <th>Uploaded by</th>
    <th>Submitted on</th>
    <th>Reviews</th>
{% endblock headings %}
{% block data %}
    {% for i in submissions %}
        <tr>
        <td>{{i.project.title}}</td>
        <td>{{i.project.created_at.strftime("%Y-%m-%d")}}</td>
        <td>{{i.project.user.username}}</td>
        <td>{{i.submitted_at.strftime("%Y-%m-%d")}}</td>
        {% if not i.evaluation %}
            <td><a class="btn btn-dark">No Reviews yet</a></td>
        {% else %}
            <td><a class="btn btn-success" href="{{url_for('projects.reviews',id=i.evaluation[0].id)}}">Check Reviews</a></td>
        {% endif %}
        </tr>
    {% endfor %}
{% endblock data %}

Project/templates/more-info/more-taken.html
{% extends "more-info/more-info-layout.html" %}
{% block label %}Projects Taken{% endblock label %}
{% block headings %}
    <th>Project's Title</th>
    <th>Taken on</th>
    <th>Teacher</th>
    <th>Submit</th>
    <th>Remove</th>
{% endblock headings %}
{% block data %}
    {% for i in projects %}
        <tr>
        <td>{{i.project.title}}</td>
        <td>{{i.taken_at.strftime("%Y-%m-%d")}}</td>
        <td>{{i.project.user.username}}</td>
        <td><a class="btn btn-info" href="{{url_for('projects.submit_proj_taken',project_taken_id=i.id,act='submitting')}}">Submit</a></td>
        <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Remove</button>
        
            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" style="color:black;" id="deleteModalLabel">Remove Project</h5>
                        <button type="button" style="margin:0.01rem;" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <form action="{{url_for('projects.remove_proj_taken',project_taken_id=i.id,act='deleting')}}" method="POST">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </div>
                    </div>
                </div>
            </div>
        
        </td>
        </tr>
    {% endfor %}
{% endblock data %}

Project/templates/more-info/more_projects.html
{% extends "more-info/more-info-layout.html" %}
{% block label %}Projects{% endblock label %}
{% block headings %}
  <th>Project's Title</th>
  <th>Upload Date</th>
  <th>Active Workers</th>
  <th>Update</th>
  <th>Delete</th>
{% endblock headings %}
{% block data %}
{% for i in projects %}
  <tr>
    <td>{{i.title}}</td>
    <td>{{i.created_at.strftime("%Y-%m-%d")}}</td>
    <td>{{i.user_count}}</td>
    <td><a class="btn btn-info" href="{{url_for('projects.update_project',project_id=i.id,act='updating')}}">Update</a></td>
    <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
    
      <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" style="color:black;" id="deleteModalLabel">Delete Project Permanently</h5>
                  <button type="button" style="margin:0.01rem;" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-footer">
                  <form action="{{url_for('projects.delete_project',project_id=i.id,act='deleting')}}" method="POST">
                      <input type="submit" class="btn btn-danger" value="Delete">
                  </form>
              </div>
              </div>
          </div>
        </div>
    
    </td>
  </tr>
  {% endfor %}
{% endblock data %}